; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = c3_mini

[env:c3_mini]
platform = platformio/espressif32@6.1.0
board = esp32-c3-devkitm-1
framework = arduino
platform_packages =
        platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.4
board_build.arduino.upstream_packages = no
#build_flags =  -DARDUINO_USB_CDC_ON_BOOT=0
build_flags =
    ; enable USB serial
                -DARDUINO_USB_CDC_ON_BOOT=1
                -DARDUINO_USB_MODE=1
monitor_speed = 115200
#monitor_port = /dev/cu.usbmodem01
upload_speed = 921600
upload_protocol = esptool
#upload_port = /dev/cu.usbmodem01
lib_deps =
    lsatan/SmartRC-CC1101-Driver-Lib@^3.0.2
    sui77/rc-switch@^2.6.4
build_src_filter = +<*> -<tx_test/> -<fan_control/>

[env:c3_mini_tx]
extends = env:c3_mini
build_src_filter = +<tx_test/*> -<sniff.ino> -<fan_control/>

[env:c3_mini_fan]
extends = env:c3_mini
lib_deps =
    ${env:c3_mini.lib_deps}
    sinricpro/SinricPro@^3.5.2
build_src_filter = +<fan_control/*> -<sniff.ino> -<tx_test/>

